#!/bin/sh

# set -eu

PATH=/bin:/usr/bin:/sbin:/usr/sbin
ROOTDIR=$(mktemp -d)
trap 'rm -rf ${ROOTDIR} /etc/aide/aide.conf.d/00-autopkgtest' 0 INT QUIT ABRT PIPE TERM

echo "root_prefix = ${ROOTDIR}" > /etc/aide/aide.conf.d/00-autopkgtest

aideinit -f 2>&1

/etc/cron.daily/aide
